CREATE GROUP ${GROUP};

CREATE USER ${MAIN_ROLE} WITH
	CREATEROLE
	IN GROUP ${GROUP}
	PASSWORD '${MAIN_ROLE_PASS}'
;

CREATE DATABASE ${DB_NAME} WITH
	OWNER = ${MAIN_ROLE}
	ENCODING = UTF8
	LOCALE = "cs_CZ.utf8"
	LC_COLLATE = "cs_CZ.utf8"
	TEMPLATE = template0
;

GRANT ALL PRIVILEGES
	ON DATABASE ${DB_NAME}
	TO ${POSTGRES_USER}
;

GRANT CONNECT
	ON DATABASE ${DB_NAME}
	TO GROUP ${GROUP}
;

CREATE TABLE _migrations (
	year INT NOT NULL,
	version INT NOT NULL
);

CREATE USER ${READONLY_ROLE} WITH
	CREATEROLE
	IN GROUP ${GROUP}
	PASSWORD '${READONLY_ROLE_PASSWORD}'
;

GRANT SELECT
	ON ALL TABLES IN SCHEMA public
	TO ${READONLY_ROLE}
;
